"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const firebase_1 = require("../config/firebase");
const errorHandler_1 = require("../middleware/errorHandler");
const auth_1 = require("../middleware/auth");
const router = (0, express_1.Router)();
// Get overall platform statistics
router.get('/', auth_1.authenticate, (0, errorHandler_1.asyncHandler)(async (req, res) => {
    const db = (0, firebase_1.getFirestore)();
    // Get counts
    const usersSnapshot = await db.collection('users').get();
    const surveysSnapshot = await db.collection('surveys').get();
    const responsesSnapshot = await db.collection('responses').get();
    const insightsSnapshot = await db.collection('insights').get();
    const activeUsers = usersSnapshot.docs.filter((doc) => doc.data().isActive === true).length;
    const organizations = new Set(usersSnapshot.docs.map((doc) => doc.data().organization).filter(Boolean)).size;
    const stats = {
        totalUsers: usersSnapshot.size,
        activeUsers,
        organizationsCount: organizations,
        totalSurveys: surveysSnapshot.size,
        totalResponses: responsesSnapshot.size,
        totalInsights: insightsSnapshot.size,
        responseRate: surveysSnapshot.size > 0 ?
            (responsesSnapshot.size / surveysSnapshot.size) * 100 : 0,
        surveyStats: {
            published: surveysSnapshot.docs.filter((doc) => doc.data().status === 'published').length,
            draft: surveysSnapshot.docs.filter((doc) => doc.data().status === 'draft').length,
            closed: surveysSnapshot.docs.filter((doc) => doc.data().status === 'closed').length
        },
        recentActivity: [
            {
                id: '1',
                type: 'survey_created',
                description: 'New survey created',
                timestamp: new Date().toISOString()
            },
            {
                id: '2',
                type: 'response_submitted',
                description: 'Survey response submitted',
                timestamp: new Date().toISOString()
            }
        ]
    };
    res.json({
        success: true,
        data: stats
    });
}));
// Get survey-specific statistics
router.get('/survey/:id', auth_1.authenticate, (0, errorHandler_1.asyncHandler)(async (req, res) => {
    const db = (0, firebase_1.getFirestore)();
    const surveyId = req.params.id;
    const surveyDoc = await db.collection('surveys').doc(surveyId).get();
    if (!surveyDoc.exists) {
        throw new errorHandler_1.AppError('Survey not found', 404);
    }
    const responsesSnapshot = await db.collection('responses')
        .where('surveyId', '==', surveyId)
        .get();
    const stats = {
        surveyId,
        totalResponses: responsesSnapshot.size,
        responseRate: 0, // Would be calculated based on target respondents
        responsesByDate: [
            {
                date: new Date().toISOString().split('T')[0],
                count: responsesSnapshot.size
            }
        ],
        questionStats: [] // Would be calculated based on question responses
    };
    res.json({
        success: true,
        data: stats
    });
}));
// Get user-specific statistics
router.get('/user/:id', auth_1.authenticate, (0, errorHandler_1.asyncHandler)(async (req, res) => {
    const db = (0, firebase_1.getFirestore)();
    const userId = req.params.id;
    const userDoc = await db.collection('users').doc(userId).get();
    if (!userDoc.exists) {
        throw new errorHandler_1.AppError('User not found', 404);
    }
    const user = Object.assign({ id: userDoc.id }, userDoc.data());
    // Get surveys created by user
    const surveysSnapshot = await db.collection('surveys')
        .where('createdBy', '==', userId)
        .get();
    // Get responses submitted by user
    const responsesSnapshot = await db.collection('responses')
        .where('respondentId', '==', userId)
        .get();
    // Get insights generated by user
    const insightsSnapshot = await db.collection('insights')
        .where('createdBy', '==', userId)
        .get();
    const stats = {
        user: {
            id: user.id,
            name: user.name,
            email: user.email,
            role: user.role,
            organization: user.organization,
            createdAt: user.createdAt,
            lastLogin: user.lastLogin
        },
        surveys: {
            total: surveysSnapshot.size,
            published: surveysSnapshot.docs.filter((doc) => doc.data().status === 'published').length,
            draft: surveysSnapshot.docs.filter((doc) => doc.data().status === 'draft').length,
            closed: surveysSnapshot.docs.filter((doc) => doc.data().status === 'closed').length
        },
        responses: {
            total: responsesSnapshot.size,
            offline: responsesSnapshot.docs.filter((doc) => doc.data().isOffline === true).length,
            online: responsesSnapshot.docs.filter((doc) => doc.data().isOffline !== true).length
        },
        insights: insightsSnapshot.size
    };
    res.json({
        success: true,
        data: stats
    });
}));
exports.default = router;
