import { Router, Response } from 'express';
import { getFirestore } from '../config/firebase';
import { ApiResponse } from '../types';
import { AuthenticatedRequest } from '../middleware/auth';
import { AppError, asyncHandler } from '../middleware/errorHandler';
import { authenticate, authorize } from '../middleware/auth';
import { UserRole } from '../types';

const router = Router();

// Get overall platform statistics
router.get('/', authenticate, asyncHandler(async (req: AuthenticatedRequest, res: Response<ApiResponse>) => {
  const db = getFirestore();

  // Get counts
  const usersSnapshot = await db.collection('users').get();
  const surveysSnapshot = await db.collection('surveys').get();
  const responsesSnapshot = await db.collection('responses').get();
  const insightsSnapshot = await db.collection('insights').get();

  const activeUsers = usersSnapshot.docs.filter((doc: any) => 
    doc.data().isActive === true
  ).length;

  const organizations = new Set(
    usersSnapshot.docs.map((doc: any) => doc.data().organization).filter(Boolean)
  ).size;

  const stats = {
    totalUsers: usersSnapshot.size,
    activeUsers,
    organizationsCount: organizations,
    totalSurveys: surveysSnapshot.size,
    totalResponses: responsesSnapshot.size,
    totalInsights: insightsSnapshot.size,
    responseRate: surveysSnapshot.size > 0 ? 
      (responsesSnapshot.size / surveysSnapshot.size) * 100 : 0,
    surveyStats: {
      published: surveysSnapshot.docs.filter((doc: any) => 
        doc.data().status === 'published'
      ).length,
      draft: surveysSnapshot.docs.filter((doc: any) => 
        doc.data().status === 'draft'
      ).length,
      closed: surveysSnapshot.docs.filter((doc: any) => 
        doc.data().status === 'closed'
      ).length
    },
    recentActivity: [
      {
        id: '1',
        type: 'survey_created',
        description: 'New survey created',
        timestamp: new Date().toISOString()
      },
      {
        id: '2',
        type: 'response_submitted',
        description: 'Survey response submitted',
        timestamp: new Date().toISOString()
      }
    ]
  };

  res.json({
    success: true,
    data: stats
  });
}));

// Get survey-specific statistics
router.get('/survey/:id', authenticate, asyncHandler(async (req: AuthenticatedRequest, res: Response<ApiResponse>) => {
  const db = getFirestore();
  const surveyId = req.params.id;

  const surveyDoc = await db.collection('surveys').doc(surveyId).get();
  
  if (!surveyDoc.exists) {
    throw new AppError('Survey not found', 404);
  }

  const responsesSnapshot = await db.collection('responses')
    .where('surveyId', '==', surveyId)
    .get();

  const stats = {
    surveyId,
    totalResponses: responsesSnapshot.size,
    responseRate: 0, // Would be calculated based on target respondents
    responsesByDate: [
      {
        date: new Date().toISOString().split('T')[0],
        count: responsesSnapshot.size
      }
    ],
    questionStats: [] // Would be calculated based on question responses
  };

  res.json({
    success: true,
    data: stats
  });
}));

// Get user-specific statistics
router.get('/user/:id', authenticate, asyncHandler(async (req: AuthenticatedRequest, res: Response<ApiResponse>) => {
  const db = getFirestore();
  const userId = req.params.id;

  const userDoc = await db.collection('users').doc(userId).get();
  
  if (!userDoc.exists) {
    throw new AppError('User not found', 404);
  }

  const user = { id: userDoc.id, ...userDoc.data() } as any;

  // Get surveys created by user
  const surveysSnapshot = await db.collection('surveys')
    .where('createdBy', '==', userId)
    .get();

  // Get responses submitted by user
  const responsesSnapshot = await db.collection('responses')
    .where('respondentId', '==', userId)
    .get();

  // Get insights generated by user
  const insightsSnapshot = await db.collection('insights')
    .where('createdBy', '==', userId)
    .get();

  const stats = {
    user: {
      id: user.id,
      name: user.name,
      email: user.email,
      role: user.role,
      organization: user.organization,
      createdAt: user.createdAt,
      lastLogin: user.lastLogin
    },
    surveys: {
      total: surveysSnapshot.size,
      published: surveysSnapshot.docs.filter((doc: any) => 
        doc.data().status === 'published'
      ).length,
      draft: surveysSnapshot.docs.filter((doc: any) => 
        doc.data().status === 'draft'
      ).length,
      closed: surveysSnapshot.docs.filter((doc: any) => 
        doc.data().status === 'closed'
      ).length
    },
    responses: {
      total: responsesSnapshot.size,
      offline: responsesSnapshot.docs.filter((doc: any) => 
        doc.data().isOffline === true
      ).length,
      online: responsesSnapshot.docs.filter((doc: any) => 
        doc.data().isOffline !== true
      ).length
    },
    insights: insightsSnapshot.size
  };

  res.json({
    success: true,
    data: stats
  });
}));

export default router;
